# Generated by Django 3.2.5 on 2021-07-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Nome'),
        ),
    ]
