# Generated by Django 3.2.5 on 2021-07-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20210706_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='logo',
            field=models.ImageField(blank=True, default='image_empty.png', null=True, upload_to=''),
        ),
    ]
